[package]
name = "chirpstack-concentratord-2g4"
repository="https://github.com/chirpstack/chirpstack-concentratord/"
description="LoRa concentrator HAL daemon (2.4GHz)"
license="MIT"
version = "4.3.4"
authors = ["Orne Brocaar <info@brocaar.com>"]
edition = "2021"
publish = false

[dependencies]
libloragw-2g4 = {path = "../libloragw-2g4"}
libconcentratord = {path = "../libconcentratord"}
chirpstack_api = { version = "4.6.0-test.1", default-features = false }
serde = { version = "1.0", features = ["derive"] }
toml = "0.8"
clap = { version = "4.4", features = ["derive"] }
log = "0.4"
simple_logger = "4.2"
zmq = "0.10"
hex = "0.4"
lazy_static = "1.4"
chrono = "0.4"
humantime-serde = "1.1"
syslog = "6.1"
prost = "0.12"
prost-types = "0.12"
signal-hook = "0.3"
handlebars = "4.4"
rand = "0.8"
anyhow = "1.0"
