[package]
name = "libloragw-sx1301"
version = "1.0.0"
authors = ["Orne Brocaar <info@brocaar.com>"]
edition = "2018"
publish = false

[dependencies]
lazy_static = "1.4"
anyhow = "1.0"

[build-dependencies]
bindgen = "0.64"
