[package]
  name = "libloragw-2g4"
  version = "1.0.0"
  authors = ["Orne Brocaar <info@brocaar.com>"]
  edition = "2021"
  publish = false

[dependencies]
  lazy_static = "1.5"
  anyhow = "1.0"

[build-dependencies]
  bindgen = "0.69"
