[package]
name = "libloragw-sx1302"
version = "1.0.0"
authors = ["Orne Brocaar <info@brocaar.com>"]
edition = "2018"
publish = false

[dependencies]
lazy_static = "1.4"

[build-dependencies]
bindgen = "0.58"
