[package]
name = "libconcentratord"
version = "4.0.1"
authors = ["Orne Brocaar <@brocaar.com>"]
edition = "2018"
publish = false

[dependencies]
log = "0.4"
zmq = "0.9"
lazy_static = "1.4"
chirpstack_api = { version = "4.0.2", default-features = false }
prost = "0.11"
pbjson-types = "0.5"
hex = "0.4"
gpio-cdev = "0.5"
anyhow = "1.0"

[features]
default = ['zmq/vendored']
