[package]
  name = "libconcentratord"
  version = "4.4.2"
  authors = ["Orne Brocaar <@brocaar.com>"]
  edition = "2021"
  publish = false

[dependencies]
  log = "0.4"
  zmq = "0.10"
  lazy_static = "1.5"
  chirpstack_api = { version = "4.9", default-features = false }
  prost = "0.13"
  prost-types = "0.13"
  hex = "0.4"
  gpio-cdev = "0.6"
  anyhow = "1.0"
  thiserror = "1.0"
  serde = { version = "1.0", features = ["derive"] }
