[package]
name = "chirpstack-concentratord-sx1302"
version = "3.2.0"
authors = ["Orne Brocaar <info@brocaar.com>"]
edition = "2018"
publish = false

[dependencies]
libloragw-sx1302 = {path = "../libloragw-sx1302"}
libconcentratord = {path = "../libconcentratord"}
chirpstack_api = { version = "3.10", default-features = false }
serde = { version = "1.0", features = ["derive"] }
toml = "0.5"
clap = "2.33"
log = "0.4"
simple_logger = "1.11"
zmq = "0.9"
hex = "0.4"
lazy_static = "1.4"
uuid = { version = "0.8", features = ["v4"] }
chrono = "0.4"
humantime-serde = "1.0"
syslog = "5.0"
prost = "0.8"
prost-types = "0.8"
signal-hook = "0.3"
handlebars = "4.1"

[features]
default = ['zmq/vendored']
